name: flutter_pk
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.0.1+20051501

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.12.9+3
  firebase_messaging: ^5.0.2
  sprung: ^1.1.0+11
  intl: '^0.15.4'
  rounded_modal: ^1.0.0
  progress_indicators: ^0.1.2
  google_sign_in: ^4.1.4
  cached_network_image: 2.0.0-rc.1
  rflutter_alert: ^1.0.2
  shared_preferences: ^0.5.6
  smooth_star_rating: 1.0.1
  barcode_scan: ^1.0.0
  #google_maps_flutter: ^0.2.0+3
  url_launcher: ^5.4.1
  qr_flutter: ^3.0.1
  font_awesome_flutter: ^8.5.0
  json_annotation: ^3.0.0
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  chopper: ^3.0.1+1
  image_picker: ^0.6.3+1
  google_fonts: ^0.3.7
  # badges for message notification
  badges: ^1.1.0
  #Provide for state managment
  provider: ^4.0.4
  firebase_storage:
    git:
      url: git://github.com/danysz/flutterfire.git
      ref: master
      path: packages/firebase_storage

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  test: ^1.9.4
  mockito: ^4.1.1
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  chopper_generator: ^3.0.1+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/wtq_icon.png"
  image_path_ios: "assets/icon/wtq_icon_ios.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Light.ttf
          weight: 300


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/logo.png
    - assets/icon/2.0x/logo.png
    - assets/icon/3.0x/logo.png
    - assets/icon/4.0x/logo.png
    - assets/icon/5.0x/logo.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
